# This is a GNU -*- Makefile -*- and you will need at least GNU make-4, and maybe make-4.2.1
# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache-2.0 license. See LICENSE file in https://github.com/yahoo/state-space-packaging/blob/master/LICENSE for terms.
default:
PACKAGES = \
  state-space-fabric-sdk-c++ \
  state-space-PrivacyChain-sdk-c++ \
  state-space-tooling \
  state-space-testing \
  state-space-packaging \
  $(end)
include ../../mk/rpmbuild/Makefrag
