# This is a GNU -*- Makefile -*- and you will need at least GNU make-4, and maybe make-4.2.1
default:
PACKAGES = \
  hyperledger-fabric-ca \
  hyperledger-fabric-orderer \
  hyperledger-fabric-peer \
  $(end)
include ../../mk/rpmbuild/Makefrag
